#What base image should we use?
FROM  <blank>

WORKDIR /app

#We want to copy over the package json to our imagine
COPY <blank> <blank>

#We want to install dependencies
RUN <blank>

#We want to expose port 3000 to our computer
EXPOSE <blank>

#Copy the rest of the code
COPY <blank> <blank>

#Run the server
CMD [ <blank>, <blank> ]
